#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackTestingPlatformTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TradeMarket201605")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertMarketData_A1605_DCE(MarketData_A1605_DCE instance);
    partial void UpdateMarketData_A1605_DCE(MarketData_A1605_DCE instance);
    partial void DeleteMarketData_A1605_DCE(MarketData_A1605_DCE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::BackTestingPlatformTest.Properties.Settings.Default.TradeMarket201605ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MarketData_A1605_DCE> MarketData_A1605_DCE
		{
			get
			{
				return this.GetTable<MarketData_A1605_DCE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MarketData_A1605_DCE")]
	public partial class MarketData_A1605_DCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _marketdataid;
		
		private int _id;
		
		private string _stkcd;
		
		private string _tdate;
		
		private string _ndate;
		
		private string _ttime;
		
		private System.Nullable<decimal> _cp;
		
		private System.Nullable<decimal> _S1;
		
		private System.Nullable<decimal> _S2;
		
		private System.Nullable<decimal> _S3;
		
		private System.Nullable<decimal> _S4;
		
		private System.Nullable<decimal> _S5;
		
		private System.Nullable<decimal> _S6;
		
		private System.Nullable<decimal> _S7;
		
		private System.Nullable<decimal> _S8;
		
		private System.Nullable<decimal> _S9;
		
		private System.Nullable<decimal> _S10;
		
		private System.Nullable<decimal> _B1;
		
		private System.Nullable<decimal> _B2;
		
		private System.Nullable<decimal> _B3;
		
		private System.Nullable<decimal> _B4;
		
		private System.Nullable<decimal> _B5;
		
		private System.Nullable<decimal> _B6;
		
		private System.Nullable<decimal> _B7;
		
		private System.Nullable<decimal> _B8;
		
		private System.Nullable<decimal> _B9;
		
		private System.Nullable<decimal> _B10;
		
		private System.Nullable<decimal> _SV1;
		
		private System.Nullable<decimal> _SV2;
		
		private System.Nullable<decimal> _SV3;
		
		private System.Nullable<decimal> _SV4;
		
		private System.Nullable<decimal> _SV5;
		
		private System.Nullable<decimal> _SV6;
		
		private System.Nullable<decimal> _SV7;
		
		private System.Nullable<decimal> _SV8;
		
		private System.Nullable<decimal> _SV9;
		
		private System.Nullable<decimal> _SV10;
		
		private System.Nullable<decimal> _BV1;
		
		private System.Nullable<decimal> _BV2;
		
		private System.Nullable<decimal> _BV3;
		
		private System.Nullable<decimal> _BV4;
		
		private System.Nullable<decimal> _BV5;
		
		private System.Nullable<decimal> _BV6;
		
		private System.Nullable<decimal> _BV7;
		
		private System.Nullable<decimal> _BV8;
		
		private System.Nullable<decimal> _BV9;
		
		private System.Nullable<decimal> _BV10;
		
		private System.Nullable<decimal> _hp;
		
		private System.Nullable<decimal> _lp;
		
		private System.Nullable<decimal> _HighLimit;
		
		private System.Nullable<decimal> _LowLimit;
		
		private System.Nullable<decimal> _ts;
		
		private System.Nullable<decimal> _tt;
		
		private System.Nullable<decimal> _OPNPRC;
		
		private System.Nullable<decimal> _PRECLOSE;
		
		private System.Nullable<decimal> _Settle;
		
		private System.Nullable<decimal> _PrevSettle;
		
		private System.Nullable<int> _CurrDelta;
		
		private System.Nullable<int> _PreDelta;
		
		private System.Nullable<int> _OpenInterest;
		
		private System.Nullable<int> _PreOpenInterest;
		
		private string _LocalRecTime;
		
		private string _TradeStatus;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmarketdataidChanging(int value);
    partial void OnmarketdataidChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstkcdChanging(string value);
    partial void OnstkcdChanged();
    partial void OntdateChanging(string value);
    partial void OntdateChanged();
    partial void OnndateChanging(string value);
    partial void OnndateChanged();
    partial void OnttimeChanging(string value);
    partial void OnttimeChanged();
    partial void OncpChanging(System.Nullable<decimal> value);
    partial void OncpChanged();
    partial void OnS1Changing(System.Nullable<decimal> value);
    partial void OnS1Changed();
    partial void OnS2Changing(System.Nullable<decimal> value);
    partial void OnS2Changed();
    partial void OnS3Changing(System.Nullable<decimal> value);
    partial void OnS3Changed();
    partial void OnS4Changing(System.Nullable<decimal> value);
    partial void OnS4Changed();
    partial void OnS5Changing(System.Nullable<decimal> value);
    partial void OnS5Changed();
    partial void OnS6Changing(System.Nullable<decimal> value);
    partial void OnS6Changed();
    partial void OnS7Changing(System.Nullable<decimal> value);
    partial void OnS7Changed();
    partial void OnS8Changing(System.Nullable<decimal> value);
    partial void OnS8Changed();
    partial void OnS9Changing(System.Nullable<decimal> value);
    partial void OnS9Changed();
    partial void OnS10Changing(System.Nullable<decimal> value);
    partial void OnS10Changed();
    partial void OnB1Changing(System.Nullable<decimal> value);
    partial void OnB1Changed();
    partial void OnB2Changing(System.Nullable<decimal> value);
    partial void OnB2Changed();
    partial void OnB3Changing(System.Nullable<decimal> value);
    partial void OnB3Changed();
    partial void OnB4Changing(System.Nullable<decimal> value);
    partial void OnB4Changed();
    partial void OnB5Changing(System.Nullable<decimal> value);
    partial void OnB5Changed();
    partial void OnB6Changing(System.Nullable<decimal> value);
    partial void OnB6Changed();
    partial void OnB7Changing(System.Nullable<decimal> value);
    partial void OnB7Changed();
    partial void OnB8Changing(System.Nullable<decimal> value);
    partial void OnB8Changed();
    partial void OnB9Changing(System.Nullable<decimal> value);
    partial void OnB9Changed();
    partial void OnB10Changing(System.Nullable<decimal> value);
    partial void OnB10Changed();
    partial void OnSV1Changing(System.Nullable<decimal> value);
    partial void OnSV1Changed();
    partial void OnSV2Changing(System.Nullable<decimal> value);
    partial void OnSV2Changed();
    partial void OnSV3Changing(System.Nullable<decimal> value);
    partial void OnSV3Changed();
    partial void OnSV4Changing(System.Nullable<decimal> value);
    partial void OnSV4Changed();
    partial void OnSV5Changing(System.Nullable<decimal> value);
    partial void OnSV5Changed();
    partial void OnSV6Changing(System.Nullable<decimal> value);
    partial void OnSV6Changed();
    partial void OnSV7Changing(System.Nullable<decimal> value);
    partial void OnSV7Changed();
    partial void OnSV8Changing(System.Nullable<decimal> value);
    partial void OnSV8Changed();
    partial void OnSV9Changing(System.Nullable<decimal> value);
    partial void OnSV9Changed();
    partial void OnSV10Changing(System.Nullable<decimal> value);
    partial void OnSV10Changed();
    partial void OnBV1Changing(System.Nullable<decimal> value);
    partial void OnBV1Changed();
    partial void OnBV2Changing(System.Nullable<decimal> value);
    partial void OnBV2Changed();
    partial void OnBV3Changing(System.Nullable<decimal> value);
    partial void OnBV3Changed();
    partial void OnBV4Changing(System.Nullable<decimal> value);
    partial void OnBV4Changed();
    partial void OnBV5Changing(System.Nullable<decimal> value);
    partial void OnBV5Changed();
    partial void OnBV6Changing(System.Nullable<decimal> value);
    partial void OnBV6Changed();
    partial void OnBV7Changing(System.Nullable<decimal> value);
    partial void OnBV7Changed();
    partial void OnBV8Changing(System.Nullable<decimal> value);
    partial void OnBV8Changed();
    partial void OnBV9Changing(System.Nullable<decimal> value);
    partial void OnBV9Changed();
    partial void OnBV10Changing(System.Nullable<decimal> value);
    partial void OnBV10Changed();
    partial void OnhpChanging(System.Nullable<decimal> value);
    partial void OnhpChanged();
    partial void OnlpChanging(System.Nullable<decimal> value);
    partial void OnlpChanged();
    partial void OnHighLimitChanging(System.Nullable<decimal> value);
    partial void OnHighLimitChanged();
    partial void OnLowLimitChanging(System.Nullable<decimal> value);
    partial void OnLowLimitChanged();
    partial void OntsChanging(System.Nullable<decimal> value);
    partial void OntsChanged();
    partial void OnttChanging(System.Nullable<decimal> value);
    partial void OnttChanged();
    partial void OnOPNPRCChanging(System.Nullable<decimal> value);
    partial void OnOPNPRCChanged();
    partial void OnPRECLOSEChanging(System.Nullable<decimal> value);
    partial void OnPRECLOSEChanged();
    partial void OnSettleChanging(System.Nullable<decimal> value);
    partial void OnSettleChanged();
    partial void OnPrevSettleChanging(System.Nullable<decimal> value);
    partial void OnPrevSettleChanged();
    partial void OnCurrDeltaChanging(System.Nullable<int> value);
    partial void OnCurrDeltaChanged();
    partial void OnPreDeltaChanging(System.Nullable<int> value);
    partial void OnPreDeltaChanged();
    partial void OnOpenInterestChanging(System.Nullable<int> value);
    partial void OnOpenInterestChanged();
    partial void OnPreOpenInterestChanging(System.Nullable<int> value);
    partial void OnPreOpenInterestChanged();
    partial void OnLocalRecTimeChanging(string value);
    partial void OnLocalRecTimeChanged();
    partial void OnTradeStatusChanging(string value);
    partial void OnTradeStatusChanged();
    #endregion
		
		public MarketData_A1605_DCE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marketdataid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int marketdataid
		{
			get
			{
				return this._marketdataid;
			}
			set
			{
				if ((this._marketdataid != value))
				{
					this.OnmarketdataidChanging(value);
					this.SendPropertyChanging();
					this._marketdataid = value;
					this.SendPropertyChanged("marketdataid");
					this.OnmarketdataidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stkcd", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string stkcd
		{
			get
			{
				return this._stkcd;
			}
			set
			{
				if ((this._stkcd != value))
				{
					this.OnstkcdChanging(value);
					this.SendPropertyChanging();
					this._stkcd = value;
					this.SendPropertyChanged("stkcd");
					this.OnstkcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tdate", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string tdate
		{
			get
			{
				return this._tdate;
			}
			set
			{
				if ((this._tdate != value))
				{
					this.OntdateChanging(value);
					this.SendPropertyChanging();
					this._tdate = value;
					this.SendPropertyChanged("tdate");
					this.OntdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndate", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string ndate
		{
			get
			{
				return this._ndate;
			}
			set
			{
				if ((this._ndate != value))
				{
					this.OnndateChanging(value);
					this.SendPropertyChanging();
					this._ndate = value;
					this.SendPropertyChanged("ndate");
					this.OnndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ttime", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string ttime
		{
			get
			{
				return this._ttime;
			}
			set
			{
				if ((this._ttime != value))
				{
					this.OnttimeChanging(value);
					this.SendPropertyChanging();
					this._ttime = value;
					this.SendPropertyChanged("ttime");
					this.OnttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cp", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> cp
		{
			get
			{
				return this._cp;
			}
			set
			{
				if ((this._cp != value))
				{
					this.OncpChanging(value);
					this.SendPropertyChanging();
					this._cp = value;
					this.SendPropertyChanged("cp");
					this.OncpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S1", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S1
		{
			get
			{
				return this._S1;
			}
			set
			{
				if ((this._S1 != value))
				{
					this.OnS1Changing(value);
					this.SendPropertyChanging();
					this._S1 = value;
					this.SendPropertyChanged("S1");
					this.OnS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S2", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S2
		{
			get
			{
				return this._S2;
			}
			set
			{
				if ((this._S2 != value))
				{
					this.OnS2Changing(value);
					this.SendPropertyChanging();
					this._S2 = value;
					this.SendPropertyChanged("S2");
					this.OnS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S3
		{
			get
			{
				return this._S3;
			}
			set
			{
				if ((this._S3 != value))
				{
					this.OnS3Changing(value);
					this.SendPropertyChanging();
					this._S3 = value;
					this.SendPropertyChanged("S3");
					this.OnS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S4", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S4
		{
			get
			{
				return this._S4;
			}
			set
			{
				if ((this._S4 != value))
				{
					this.OnS4Changing(value);
					this.SendPropertyChanging();
					this._S4 = value;
					this.SendPropertyChanged("S4");
					this.OnS4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S5", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S5
		{
			get
			{
				return this._S5;
			}
			set
			{
				if ((this._S5 != value))
				{
					this.OnS5Changing(value);
					this.SendPropertyChanging();
					this._S5 = value;
					this.SendPropertyChanged("S5");
					this.OnS5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S6", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S6
		{
			get
			{
				return this._S6;
			}
			set
			{
				if ((this._S6 != value))
				{
					this.OnS6Changing(value);
					this.SendPropertyChanging();
					this._S6 = value;
					this.SendPropertyChanged("S6");
					this.OnS6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S7", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S7
		{
			get
			{
				return this._S7;
			}
			set
			{
				if ((this._S7 != value))
				{
					this.OnS7Changing(value);
					this.SendPropertyChanging();
					this._S7 = value;
					this.SendPropertyChanged("S7");
					this.OnS7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S8", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S8
		{
			get
			{
				return this._S8;
			}
			set
			{
				if ((this._S8 != value))
				{
					this.OnS8Changing(value);
					this.SendPropertyChanging();
					this._S8 = value;
					this.SendPropertyChanged("S8");
					this.OnS8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S9", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S9
		{
			get
			{
				return this._S9;
			}
			set
			{
				if ((this._S9 != value))
				{
					this.OnS9Changing(value);
					this.SendPropertyChanging();
					this._S9 = value;
					this.SendPropertyChanged("S9");
					this.OnS9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S10", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> S10
		{
			get
			{
				return this._S10;
			}
			set
			{
				if ((this._S10 != value))
				{
					this.OnS10Changing(value);
					this.SendPropertyChanging();
					this._S10 = value;
					this.SendPropertyChanged("S10");
					this.OnS10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B1", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B1
		{
			get
			{
				return this._B1;
			}
			set
			{
				if ((this._B1 != value))
				{
					this.OnB1Changing(value);
					this.SendPropertyChanging();
					this._B1 = value;
					this.SendPropertyChanged("B1");
					this.OnB1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B2", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B2
		{
			get
			{
				return this._B2;
			}
			set
			{
				if ((this._B2 != value))
				{
					this.OnB2Changing(value);
					this.SendPropertyChanging();
					this._B2 = value;
					this.SendPropertyChanged("B2");
					this.OnB2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B3", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B3
		{
			get
			{
				return this._B3;
			}
			set
			{
				if ((this._B3 != value))
				{
					this.OnB3Changing(value);
					this.SendPropertyChanging();
					this._B3 = value;
					this.SendPropertyChanged("B3");
					this.OnB3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B4", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B4
		{
			get
			{
				return this._B4;
			}
			set
			{
				if ((this._B4 != value))
				{
					this.OnB4Changing(value);
					this.SendPropertyChanging();
					this._B4 = value;
					this.SendPropertyChanged("B4");
					this.OnB4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B5", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B5
		{
			get
			{
				return this._B5;
			}
			set
			{
				if ((this._B5 != value))
				{
					this.OnB5Changing(value);
					this.SendPropertyChanging();
					this._B5 = value;
					this.SendPropertyChanged("B5");
					this.OnB5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B6", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B6
		{
			get
			{
				return this._B6;
			}
			set
			{
				if ((this._B6 != value))
				{
					this.OnB6Changing(value);
					this.SendPropertyChanging();
					this._B6 = value;
					this.SendPropertyChanged("B6");
					this.OnB6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B7", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B7
		{
			get
			{
				return this._B7;
			}
			set
			{
				if ((this._B7 != value))
				{
					this.OnB7Changing(value);
					this.SendPropertyChanging();
					this._B7 = value;
					this.SendPropertyChanged("B7");
					this.OnB7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B8", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B8
		{
			get
			{
				return this._B8;
			}
			set
			{
				if ((this._B8 != value))
				{
					this.OnB8Changing(value);
					this.SendPropertyChanging();
					this._B8 = value;
					this.SendPropertyChanged("B8");
					this.OnB8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B9", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B9
		{
			get
			{
				return this._B9;
			}
			set
			{
				if ((this._B9 != value))
				{
					this.OnB9Changing(value);
					this.SendPropertyChanging();
					this._B9 = value;
					this.SendPropertyChanged("B9");
					this.OnB9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B10", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> B10
		{
			get
			{
				return this._B10;
			}
			set
			{
				if ((this._B10 != value))
				{
					this.OnB10Changing(value);
					this.SendPropertyChanging();
					this._B10 = value;
					this.SendPropertyChanged("B10");
					this.OnB10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV1
		{
			get
			{
				return this._SV1;
			}
			set
			{
				if ((this._SV1 != value))
				{
					this.OnSV1Changing(value);
					this.SendPropertyChanging();
					this._SV1 = value;
					this.SendPropertyChanged("SV1");
					this.OnSV1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV2", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV2
		{
			get
			{
				return this._SV2;
			}
			set
			{
				if ((this._SV2 != value))
				{
					this.OnSV2Changing(value);
					this.SendPropertyChanging();
					this._SV2 = value;
					this.SendPropertyChanged("SV2");
					this.OnSV2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV3", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV3
		{
			get
			{
				return this._SV3;
			}
			set
			{
				if ((this._SV3 != value))
				{
					this.OnSV3Changing(value);
					this.SendPropertyChanging();
					this._SV3 = value;
					this.SendPropertyChanged("SV3");
					this.OnSV3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV4", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV4
		{
			get
			{
				return this._SV4;
			}
			set
			{
				if ((this._SV4 != value))
				{
					this.OnSV4Changing(value);
					this.SendPropertyChanging();
					this._SV4 = value;
					this.SendPropertyChanged("SV4");
					this.OnSV4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV5", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV5
		{
			get
			{
				return this._SV5;
			}
			set
			{
				if ((this._SV5 != value))
				{
					this.OnSV5Changing(value);
					this.SendPropertyChanging();
					this._SV5 = value;
					this.SendPropertyChanged("SV5");
					this.OnSV5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV6", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV6
		{
			get
			{
				return this._SV6;
			}
			set
			{
				if ((this._SV6 != value))
				{
					this.OnSV6Changing(value);
					this.SendPropertyChanging();
					this._SV6 = value;
					this.SendPropertyChanged("SV6");
					this.OnSV6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV7", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV7
		{
			get
			{
				return this._SV7;
			}
			set
			{
				if ((this._SV7 != value))
				{
					this.OnSV7Changing(value);
					this.SendPropertyChanging();
					this._SV7 = value;
					this.SendPropertyChanged("SV7");
					this.OnSV7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV8", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV8
		{
			get
			{
				return this._SV8;
			}
			set
			{
				if ((this._SV8 != value))
				{
					this.OnSV8Changing(value);
					this.SendPropertyChanging();
					this._SV8 = value;
					this.SendPropertyChanged("SV8");
					this.OnSV8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV9", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV9
		{
			get
			{
				return this._SV9;
			}
			set
			{
				if ((this._SV9 != value))
				{
					this.OnSV9Changing(value);
					this.SendPropertyChanging();
					this._SV9 = value;
					this.SendPropertyChanged("SV9");
					this.OnSV9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV10", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SV10
		{
			get
			{
				return this._SV10;
			}
			set
			{
				if ((this._SV10 != value))
				{
					this.OnSV10Changing(value);
					this.SendPropertyChanging();
					this._SV10 = value;
					this.SendPropertyChanged("SV10");
					this.OnSV10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV1", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV1
		{
			get
			{
				return this._BV1;
			}
			set
			{
				if ((this._BV1 != value))
				{
					this.OnBV1Changing(value);
					this.SendPropertyChanging();
					this._BV1 = value;
					this.SendPropertyChanged("BV1");
					this.OnBV1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV2", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV2
		{
			get
			{
				return this._BV2;
			}
			set
			{
				if ((this._BV2 != value))
				{
					this.OnBV2Changing(value);
					this.SendPropertyChanging();
					this._BV2 = value;
					this.SendPropertyChanged("BV2");
					this.OnBV2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV3", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV3
		{
			get
			{
				return this._BV3;
			}
			set
			{
				if ((this._BV3 != value))
				{
					this.OnBV3Changing(value);
					this.SendPropertyChanging();
					this._BV3 = value;
					this.SendPropertyChanged("BV3");
					this.OnBV3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV4", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV4
		{
			get
			{
				return this._BV4;
			}
			set
			{
				if ((this._BV4 != value))
				{
					this.OnBV4Changing(value);
					this.SendPropertyChanging();
					this._BV4 = value;
					this.SendPropertyChanged("BV4");
					this.OnBV4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV5", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV5
		{
			get
			{
				return this._BV5;
			}
			set
			{
				if ((this._BV5 != value))
				{
					this.OnBV5Changing(value);
					this.SendPropertyChanging();
					this._BV5 = value;
					this.SendPropertyChanged("BV5");
					this.OnBV5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV6", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV6
		{
			get
			{
				return this._BV6;
			}
			set
			{
				if ((this._BV6 != value))
				{
					this.OnBV6Changing(value);
					this.SendPropertyChanging();
					this._BV6 = value;
					this.SendPropertyChanged("BV6");
					this.OnBV6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV7", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV7
		{
			get
			{
				return this._BV7;
			}
			set
			{
				if ((this._BV7 != value))
				{
					this.OnBV7Changing(value);
					this.SendPropertyChanging();
					this._BV7 = value;
					this.SendPropertyChanged("BV7");
					this.OnBV7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV8", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV8
		{
			get
			{
				return this._BV8;
			}
			set
			{
				if ((this._BV8 != value))
				{
					this.OnBV8Changing(value);
					this.SendPropertyChanging();
					this._BV8 = value;
					this.SendPropertyChanged("BV8");
					this.OnBV8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV9", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV9
		{
			get
			{
				return this._BV9;
			}
			set
			{
				if ((this._BV9 != value))
				{
					this.OnBV9Changing(value);
					this.SendPropertyChanging();
					this._BV9 = value;
					this.SendPropertyChanged("BV9");
					this.OnBV9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BV10", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> BV10
		{
			get
			{
				return this._BV10;
			}
			set
			{
				if ((this._BV10 != value))
				{
					this.OnBV10Changing(value);
					this.SendPropertyChanging();
					this._BV10 = value;
					this.SendPropertyChanged("BV10");
					this.OnBV10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hp", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> hp
		{
			get
			{
				return this._hp;
			}
			set
			{
				if ((this._hp != value))
				{
					this.OnhpChanging(value);
					this.SendPropertyChanging();
					this._hp = value;
					this.SendPropertyChanged("hp");
					this.OnhpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lp", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> lp
		{
			get
			{
				return this._lp;
			}
			set
			{
				if ((this._lp != value))
				{
					this.OnlpChanging(value);
					this.SendPropertyChanging();
					this._lp = value;
					this.SendPropertyChanged("lp");
					this.OnlpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighLimit", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> HighLimit
		{
			get
			{
				return this._HighLimit;
			}
			set
			{
				if ((this._HighLimit != value))
				{
					this.OnHighLimitChanging(value);
					this.SendPropertyChanging();
					this._HighLimit = value;
					this.SendPropertyChanged("HighLimit");
					this.OnHighLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowLimit", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> LowLimit
		{
			get
			{
				return this._LowLimit;
			}
			set
			{
				if ((this._LowLimit != value))
				{
					this.OnLowLimitChanging(value);
					this.SendPropertyChanging();
					this._LowLimit = value;
					this.SendPropertyChanged("LowLimit");
					this.OnLowLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt", DbType="Decimal(20,3)")]
		public System.Nullable<decimal> tt
		{
			get
			{
				return this._tt;
			}
			set
			{
				if ((this._tt != value))
				{
					this.OnttChanging(value);
					this.SendPropertyChanging();
					this._tt = value;
					this.SendPropertyChanged("tt");
					this.OnttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPNPRC", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> OPNPRC
		{
			get
			{
				return this._OPNPRC;
			}
			set
			{
				if ((this._OPNPRC != value))
				{
					this.OnOPNPRCChanging(value);
					this.SendPropertyChanging();
					this._OPNPRC = value;
					this.SendPropertyChanged("OPNPRC");
					this.OnOPNPRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECLOSE", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> PRECLOSE
		{
			get
			{
				return this._PRECLOSE;
			}
			set
			{
				if ((this._PRECLOSE != value))
				{
					this.OnPRECLOSEChanging(value);
					this.SendPropertyChanging();
					this._PRECLOSE = value;
					this.SendPropertyChanged("PRECLOSE");
					this.OnPRECLOSEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settle", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> Settle
		{
			get
			{
				return this._Settle;
			}
			set
			{
				if ((this._Settle != value))
				{
					this.OnSettleChanging(value);
					this.SendPropertyChanging();
					this._Settle = value;
					this.SendPropertyChanged("Settle");
					this.OnSettleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrevSettle", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> PrevSettle
		{
			get
			{
				return this._PrevSettle;
			}
			set
			{
				if ((this._PrevSettle != value))
				{
					this.OnPrevSettleChanging(value);
					this.SendPropertyChanging();
					this._PrevSettle = value;
					this.SendPropertyChanged("PrevSettle");
					this.OnPrevSettleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrDelta", DbType="Int")]
		public System.Nullable<int> CurrDelta
		{
			get
			{
				return this._CurrDelta;
			}
			set
			{
				if ((this._CurrDelta != value))
				{
					this.OnCurrDeltaChanging(value);
					this.SendPropertyChanging();
					this._CurrDelta = value;
					this.SendPropertyChanged("CurrDelta");
					this.OnCurrDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreDelta", DbType="Int")]
		public System.Nullable<int> PreDelta
		{
			get
			{
				return this._PreDelta;
			}
			set
			{
				if ((this._PreDelta != value))
				{
					this.OnPreDeltaChanging(value);
					this.SendPropertyChanging();
					this._PreDelta = value;
					this.SendPropertyChanged("PreDelta");
					this.OnPreDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenInterest", DbType="Int")]
		public System.Nullable<int> OpenInterest
		{
			get
			{
				return this._OpenInterest;
			}
			set
			{
				if ((this._OpenInterest != value))
				{
					this.OnOpenInterestChanging(value);
					this.SendPropertyChanging();
					this._OpenInterest = value;
					this.SendPropertyChanged("OpenInterest");
					this.OnOpenInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpenInterest", DbType="Int")]
		public System.Nullable<int> PreOpenInterest
		{
			get
			{
				return this._PreOpenInterest;
			}
			set
			{
				if ((this._PreOpenInterest != value))
				{
					this.OnPreOpenInterestChanging(value);
					this.SendPropertyChanging();
					this._PreOpenInterest = value;
					this.SendPropertyChanged("PreOpenInterest");
					this.OnPreOpenInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalRecTime", DbType="Char(9)")]
		public string LocalRecTime
		{
			get
			{
				return this._LocalRecTime;
			}
			set
			{
				if ((this._LocalRecTime != value))
				{
					this.OnLocalRecTimeChanging(value);
					this.SendPropertyChanging();
					this._LocalRecTime = value;
					this.SendPropertyChanged("LocalRecTime");
					this.OnLocalRecTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeStatus", DbType="Char(3)")]
		public string TradeStatus
		{
			get
			{
				return this._TradeStatus;
			}
			set
			{
				if ((this._TradeStatus != value))
				{
					this.OnTradeStatusChanging(value);
					this.SendPropertyChanging();
					this._TradeStatus = value;
					this.SendPropertyChanged("TradeStatus");
					this.OnTradeStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
