//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackTestingPlatformTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketData_ZN1705_SHF
    {
        public int marketdataid { get; set; }
        public int id { get; set; }
        public string stkcd { get; set; }
        public string tdate { get; set; }
        public string ndate { get; set; }
        public string ttime { get; set; }
        public Nullable<decimal> cp { get; set; }
        public Nullable<decimal> S1 { get; set; }
        public Nullable<decimal> S2 { get; set; }
        public Nullable<decimal> S3 { get; set; }
        public Nullable<decimal> S4 { get; set; }
        public Nullable<decimal> S5 { get; set; }
        public Nullable<decimal> S6 { get; set; }
        public Nullable<decimal> S7 { get; set; }
        public Nullable<decimal> S8 { get; set; }
        public Nullable<decimal> S9 { get; set; }
        public Nullable<decimal> S10 { get; set; }
        public Nullable<decimal> B1 { get; set; }
        public Nullable<decimal> B2 { get; set; }
        public Nullable<decimal> B3 { get; set; }
        public Nullable<decimal> B4 { get; set; }
        public Nullable<decimal> B5 { get; set; }
        public Nullable<decimal> B6 { get; set; }
        public Nullable<decimal> B7 { get; set; }
        public Nullable<decimal> B8 { get; set; }
        public Nullable<decimal> B9 { get; set; }
        public Nullable<decimal> B10 { get; set; }
        public Nullable<decimal> SV1 { get; set; }
        public Nullable<decimal> SV2 { get; set; }
        public Nullable<decimal> SV3 { get; set; }
        public Nullable<decimal> SV4 { get; set; }
        public Nullable<decimal> SV5 { get; set; }
        public Nullable<decimal> SV6 { get; set; }
        public Nullable<decimal> SV7 { get; set; }
        public Nullable<decimal> SV8 { get; set; }
        public Nullable<decimal> SV9 { get; set; }
        public Nullable<decimal> SV10 { get; set; }
        public Nullable<decimal> BV1 { get; set; }
        public Nullable<decimal> BV2 { get; set; }
        public Nullable<decimal> BV3 { get; set; }
        public Nullable<decimal> BV4 { get; set; }
        public Nullable<decimal> BV5 { get; set; }
        public Nullable<decimal> BV6 { get; set; }
        public Nullable<decimal> BV7 { get; set; }
        public Nullable<decimal> BV8 { get; set; }
        public Nullable<decimal> BV9 { get; set; }
        public Nullable<decimal> BV10 { get; set; }
        public Nullable<decimal> hp { get; set; }
        public Nullable<decimal> lp { get; set; }
        public Nullable<decimal> HighLimit { get; set; }
        public Nullable<decimal> LowLimit { get; set; }
        public Nullable<decimal> ts { get; set; }
        public Nullable<decimal> tt { get; set; }
        public Nullable<decimal> OPNPRC { get; set; }
        public Nullable<decimal> PRECLOSE { get; set; }
        public Nullable<decimal> Settle { get; set; }
        public Nullable<decimal> PrevSettle { get; set; }
        public Nullable<int> CurrDelta { get; set; }
        public Nullable<int> PreDelta { get; set; }
        public Nullable<int> OpenInterest { get; set; }
        public Nullable<int> PreOpenInterest { get; set; }
        public string LocalRecTime { get; set; }
        public string TradeStatus { get; set; }
    }
}
